import "./globals.css";
//Uso del componente STRICMODE para  
//habilitar comportamientos de compilación y advertencias adicionales 
import { StrictMode } from 'react';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StrictMode>
          {children}
        </StrictMode>
      </body>
    </html>
  );
}
